CREATE TABLE carros (
    id INTEGER NOT NULL AUTO_INCREMENT,
    marca VARCHAR(20) NOT NULL,
    modelo VARCHAR(20) NOT NULL,
    motor VARCHAR(1) NOT NULL, 
    cor VARCHAR(1) NOT NULL,   
    ano INTEGER NOT NULL,
    CONSTRAINT pk_carros PRIMARY KEY (id)
);
